apiVersion: v2
name: angular-web-app
description: A Helm chart for Angular Web App
type: application
version: 0.1.0
appVersion: "1.0.0"
# dependencies:
#   - name: helm-template-001
#     version: 0.1.4
#     repository: https://code360Pro.github.io/helm-template-001/

